version: "3"

services:
  api:
    container_name: api
    environment:
      - PORT=5000
      - ORIGIN=https://www.development.com/
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
    ports:
      - 5000:5000
    build: .
    volumes:
      - .:/app
      - /app/node_modules/
    command: npm run start:dev
    depends_on:
      - mongo
      - redis
    networks:
      - blog

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
    restart: always
    networks:
      - blog

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    extra_hosts:
      - "localhost:162.242.195.82"
    restart: always
    networks:
      - blog

networks:
  blog:
    driver: bridge

volumes:
  mongo_volume:
    driver: local
